# docker run -it oeliks-web

version: "3.8"

services:
  web:
    container_name: inteleld-web
    image: ghcr.io/dragonsteam/inteleld-web:latest
    build: .
    command: npm run build

    # volumes:
    #   - dist:/app/dist
# volumes:
#   dist:
