export const STATES = [
  { value: 1, label: 'Alaska' },
  { value: 2, label: 'Alabama' },
  { value: 3, label: 'Arkansas' },
  { value: 4, label: 'American Samoa' },
  { value: 5, label: 'Arizona' },
  { value: 6, label: 'California' },
  { value: 7, label: 'Colorado' },
  { value: 8, label: 'Connecticut' },
  { value: 9, label: 'District of Columbia' },
  { value: 10, label: 'Delaware' },
  { value: 11, label: 'Florida' },
  { value: 12, label: 'Georgia' },
  { value: 13, label: 'Guam' },
  { value: 14, label: 'Hawaii' },
  { value: 15, label: 'Iowa' },
  { value: 16, label: 'Idaho' },
  { value: 17, label: 'Illinois' },
  { value: 18, label: 'Indiana' },
  { value: 19, label: 'Kansas' },
  { value: 20, label: 'Kentucky' },
  { value: 21, label: 'Louisiana' },
  { value: 22, label: 'Massachusetts' },
  { value: 23, label: 'Maryland' },
  { value: 24, label: 'Maine' },
  { value: 25, label: 'Michigan' },
  { value: 26, label: 'Minnesota' },
  { value: 27, label: 'Missouri' },
  { value: 28, label: 'Mississippi' },
  { value: 29, label: 'Montana' },
  { value: 30, label: 'North Carolina' },
  { value: 31, label: 'North Dakota' },
  { value: 32, label: 'Nebraska' },
  { value: 33, label: 'New Hampshire' },
  { value: 34, label: 'New Jersey' },
  { value: 35, label: 'New Mexico' },
  { value: 36, label: 'Nevada' },
  { value: 37, label: 'New York' },
  { value: 38, label: 'Ohio' },
  { value: 39, label: 'Oklahoma' },
  { value: 40, label: 'Oregon' },
  { value: 41, label: 'Pennsylvania' },
  { value: 42, label: 'Puerto Rico' },
  { value: 43, label: 'Rhode Island' },
  { value: 44, label: 'South Carolina' },
  { value: 45, label: 'South Dakota' },
  { value: 46, label: 'Tennessee' },
  { value: 47, label: 'Texas' },
  { value: 48, label: 'Utah' },
  { value: 49, label: 'Virginia' },
  { value: 50, label: 'Virgin Islands' },
  { value: 51, label: 'Vermont' },
  { value: 52, label: 'Washington' },
  { value: 53, label: 'Wisconsin' },
  { value: 54, label: 'West Virginia' },
  { value: 55, label: 'Wyoming' },
];
