export const DATA_SERVICE_NAMES = [{ value: 'sa', name: 'Samsara' }];

export const STATES = [
  { value: 1, name: 'Alaska' },
  { value: 2, name: 'Alabama' },
  { value: 3, name: 'Arkansas' },
  { value: 4, name: 'American Samoa' },
  { value: 5, name: 'Arizona' },
  { value: 6, name: 'California' },
  { value: 7, name: 'Colorado' },
  { value: 8, name: 'Connecticut' },
  { value: 9, name: 'District of Columbia' },
  { value: 10, name: 'Delaware' },
  { value: 11, name: 'Florida' },
  { value: 12, name: 'Georgia' },
  { value: 13, name: 'Guam' },
  { value: 14, name: 'Hawaii' },
  { value: 15, name: 'Iowa' },
  { value: 16, name: 'Idaho' },
  { value: 17, name: 'Illinois' },
  { value: 18, name: 'Indiana' },
  { value: 19, name: 'Kansas' },
  { value: 20, name: 'Kentucky' },
  { value: 21, name: 'Louisiana' },
  { value: 22, name: 'Massachusetts' },
  { value: 23, name: 'Maryland' },
  { value: 24, name: 'Maine' },
  { value: 25, name: 'Michigan' },
  { value: 26, name: 'Minnesota' },
  { value: 27, name: 'Missouri' },
  { value: 28, name: 'Mississippi' },
  { value: 29, name: 'Montana' },
  { value: 30, name: 'North Carolina' },
  { value: 31, name: 'North Dakota' },
  { value: 32, name: 'Nebraska' },
  { value: 33, name: 'New Hampshire' },
  { value: 34, name: 'New Jersey' },
  { value: 35, name: 'New Mexico' },
  { value: 36, name: 'Nevada' },
  { value: 37, name: 'New York' },
  { value: 38, name: 'Ohio' },
  { value: 39, name: 'Oklahoma' },
  { value: 40, name: 'Oregon' },
  { value: 41, name: 'Pennsylvania' },
  { value: 42, name: 'Puerto Rico' },
  { value: 43, name: 'Rhode Island' },
  { value: 44, name: 'South Carolina' },
  { value: 45, name: 'South Dakota' },
  { value: 46, name: 'Tennessee' },
  { value: 47, name: 'Texas' },
  { value: 48, name: 'Utah' },
  { value: 49, name: 'Virginia' },
  { value: 50, name: 'Virgin Islands' },
  { value: 51, name: 'Vermont' },
  { value: 52, name: 'Washington' },
  { value: 53, name: 'Wisconsin' },
  { value: 54, name: 'West Virginia' },
  { value: 55, name: 'Wyoming' },
];
