export const RESET_STATE = 'MAP_RESET_STATE';

export const REQUEST_LOADING = 'MAP_REQUEST_LOADING';
export const REQUEST_SUCCESS = 'MAP_REQUEST_SUCCESS';
export const REQUEST_FAILED = 'MAP_REQUEST_FAILED';

export const OPEN_SIDE_PANEL = 'MAP_OPEN_SIDE_PANEL';
export const CLOSE_SIDE_PANEL = 'MAP_CLOSE_SIDE_PANEL';
