export const STATES = [
  { value: "AK", name: "Alaska" },
  { value: "AL", name: "Alabama" },
  { value: "AR", name: "Arkansas" },
  { value: "AS", name: "American Samoa" },
  { value: "AZ", name: "Arizona" },
  { value: "CA", name: "California" },
  { value: "CO", name: "Colorado" },
  { value: "CT", name: "Connecticut" },
  { value: "DC", name: "District of Columbia" },
  { value: "DE", name: "Delaware" },
  { value: "FL", name: "Florida" },
  { value: "GA", name: "Georgia" },
  { value: "GU", name: "Guam" },
  { value: "HI", name: "Hawaii" },
  { value: "IA", name: "Iowa" },
  { value: "ID", name: "Idaho" },
  { value: "IL", name: "Illinois" },
  { value: "IN", name: "Indiana" },
  { value: "KS", name: "Kansas" },
  { value: "KY", name: "Kentucky" },
  { value: "LA", name: "Louisiana" },
  { value: "MA", name: "Massachusetts" },
  { value: "MD", name: "Maryland" },
  { value: "ME", name: "Maine" },
  { value: "MI", name: "Michigan" },
  { value: "MN", name: "Minnesota" },
  { value: "MO", name: "Missouri" },
  { value: "MS", name: "Mississippi" },
  { value: "MT", name: "Montana" },
  { value: "NC", name: "North Carolina" },
  { value: "ND", name: "North Dakota" },
  { value: "NE", name: "Nebraska" },
  { value: "NH", name: "New Hampshire" },
  { value: "NJ", name: "New Jersey" },
  { value: "NM", name: "New Mexico" },
  { value: "NV", name: "Nevada" },
  { value: "NY", name: "New York" },
  { value: "OH", name: "Ohio" },
  { value: "OK", name: "Oklahoma" },
  { value: "OR", name: "Oregon" },
  { value: "PA", name: "Pennsylvania" },
  { value: "PR", name: "Puerto Rico" },
  { value: "RI", name: "Rhode Island" },
  { value: "SC", name: "South Carolina" },
  { value: "SD", name: "South Dakota" },
  { value: "TN", name: "Tennessee" },
  { value: "TX", name: "Texas" },
  { value: "UT", name: "Utah" },
  { value: "VA", name: "Virginia" },
  { value: "VI", name: "Virgin Islands" },
  { value: "VT", name: "Vermont" },
  { value: "WA", name: "Washington" },
  { value: "WI", name: "Wisconsin" },
  { value: "WV", name: "West Virginia" },
  { value: "WY", name: "Wyoming" },
];

export const YEARS = [
  { value: "Y12", name: "2012" },
  { value: "Y13", name: "2013" },
  { value: "Y14", name: "2014" },
  { value: "Y15", name: "2015" },
  { value: "Y16", name: "2016" },
  { value: "Y17", name: "2017" },
  { value: "Y18", name: "2018" },
  { value: "Y19", name: "2019" },
  { value: "Y20", name: "2020" },
  { value: "Y21", name: "2021" },
  { value: "Y22", name: "2022" },
  { value: "Y23", name: "2023" },
  { value: "Y24", name: "2024" },
  { value: "Y25", name: "2025" },
  { value: "Y26", name: "2026" },
  { value: "Y27", name: "2027" },
];

export const FUEL_TYPE = [
  { value: "di", name: "Diesel" },
  { value: "ga", name: "Gasoline" },
  { value: "pr", name: "Propane" },
  { value: "li", name: "Liquid Natural Gas" },
  { value: "co", name: "Compressed Natural Gas" },
  { value: "me", name: "Methanol" },
  { value: "e", name: "E-85" },
  { value: "m", name: "M-85" },
  { value: "a", name: "A55" },
  { value: "bi", name: "Biodisel" },
  { value: "o", name: "Other" },
];
