name: Docker Image CI

on:
  push:
    branches: ['main']
  # pull_request:
  #   branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dragonsteam/inteleld-web:latest

jobs:
  publish:
    name: publish image
    runs-on: self-hosted
    # runs-on: ubuntu:latest

    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u dragonsteam --password-stdin
      - name: Build and Publish
        run: |
          docker build . --file Dockerfile.prod --tag ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
          docker push ${{env.REGISTRY}}/${{env.IMAGE_NAME}}

  trigger-deploy:
    needs: publish
    name: Trigger Deploy
    runs-on: self-hosted

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: dragonsteam/inteleld
          event-type: deploy-event
