name: Trigger Deploy Action

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  trigger-next-action:
    runs-on: self-hosted
    steps:
      - name: Trigger
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: dragonsteam/inteleld
          event-type: deploy-event
